-- Needed for gen_random_uuid()
create extension if not exists pgcrypto;

-- Execution order:
--   1) Tables + Indexes
--   2) Functions + Triggers
--   3) Grants
--   4) RLS enablement
--   5) Policies




----------------------- Tables


-- Course catalog metadata
create table if not exists public.catalog (
  id uuid primary key default gen_random_uuid(),
  "createdAt" timestamp with time zone default now(),
  "createdBy" uuid references auth.users(id) on delete set null default auth.uid(),
  title text,
  description text,
  name text,
  "gitHub" jsonb default '{}'::jsonb,
  settings jsonb default '{}'::jsonb
);

-- Profile row for each authenticated user
create table if not exists public."user" (
  id uuid not null references auth.users(id) on delete cascade,
  "createdAt" timestamp with time zone default now(),
  name text,
  email text,
  settings jsonb default '{}'::jsonb,
  primary key (id)
);

-- Role assignments (root/editor, etc.)
create table if not exists public.role (
  id bigint generated by default as identity primary key,
  "createdAt" timestamp with time zone default now(),
  "user" uuid references auth.users(id) on delete cascade,
  "right" varchar,
  object uuid references public.catalog(id) on delete cascade,
  settings jsonb default '{}'::jsonb
);

-- User enrollment in a catalog/course
create table if not exists public.enrollment (
  id uuid primary key default gen_random_uuid(),
  "createdAt" timestamp with time zone default now(),
  "learnerId" uuid references public."user"(id) on delete cascade,
  "catalogId" uuid references public.catalog(id) on delete cascade,
  progress jsonb default '{}'::jsonb,
  settings jsonb default '{}'::jsonb
);

-- Speeds the mastery-overview roster query, which scopes a course's enrollments to an
-- "enrolled between" window (catalogId + createdAt range).
create index if not exists enrollment_catalog_created_idx on public.enrollment ("catalogId", "createdAt");

-- Topic content cache with full-text search index source column
create table if not exists public.topic (
  id uuid primary key,
  "catalogId" uuid references public.catalog(id) on delete cascade,
  content text not null,
  ftsContent tsvector generated always as (to_tsvector('english', ' ' || content)) stored,
  "updatedAt" timestamp with time zone default now()
);

-- Progress/event tracking per user/topic
create table if not exists public.progress (
  id uuid primary key default gen_random_uuid(),
  "createdAt" timestamp with time zone default now(),
  "userId" uuid references public."user"(id) on delete cascade,
  "enrollmentId" uuid references public.enrollment(id) on delete cascade,
  "catalogId" uuid references public.catalog(id) on delete cascade,
  "topicId" uuid,
  "interactionId" uuid,
  duration integer,
  type varchar,
  details jsonb default '{}'::jsonb
);

-- Generic append-only application event log. Any registered user can write an entry;
-- only root/editor can read them back.
create table if not exists public.log (
  id uuid primary key default gen_random_uuid(),
  event text not null,
  data jsonb default '{}'::jsonb,
  "createdAt" timestamp with time zone default now(),
  "generatedBy" uuid references auth.users(id) on delete set null default auth.uid()
);


----------------------- Indexes


-- Full-text search GIN index
create index if not exists "topicFtsIdx" on public.topic using gin (ftsContent);

-- Auth checks in gradebookoverview edge function
create index if not exists "roleUserRightObjectIdx" on public.role ("user", "right", object);

-- Course ownership bootstrap checks during editor course creation
create index if not exists "catalogCreatedByIdx" on public.catalog ("createdBy");

-- Enrollment lookups by course, and learner auth check
create index if not exists "enrollmentCatalogIdx" on public.enrollment ("catalogId");
create index if not exists "enrollmentCatalogLearnerIdx" on public.enrollment ("catalogId", "learnerId");

-- Progress queries: by enrollment+type (detail view, interaction history, notes, exam state)
create index if not exists "progressEnrollmentTypeIdx" on public.progress ("enrollmentId", type);

-- Progress queries: by catalog+topic+interaction (survey/Likert summaries)
create index if not exists "progressCatalogTopicIdx" on public.progress ("catalogId", "topicId", "interactionId");

-- Progress queries: course-scoped activity pages ordered by newest first
create index if not exists "progressCatalogCreatedAtIdx" on public.progress ("catalogId", "createdAt" desc);

-- Log queries: recent events ordered by newest first, optionally filtered by event type
create index if not exists "logCreatedAtIdx" on public.log ("createdAt" desc);
create index if not exists "logEventIdx" on public.log (event);


----------------------- Functions


-- Trigger function to keep topic updated timestamp current
create or replace function public."updateModifiedColumn"()
returns trigger
language plpgsql
as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$;

-- RPC: record a learner progress event and merge the enrollment progress cache
-- against the current database row in one transaction. This avoids stale client
-- enrollment snapshots overwriting newer nested progress, especially scores.
drop function if exists public.record_progress_event(uuid, uuid, uuid, uuid, uuid, text, integer, jsonb, jsonb, jsonb, boolean);

create or replace function public.record_progress_event(
  p_user_id uuid,
  p_catalog_id uuid,
  p_enrollment_id uuid,
  p_topic_id uuid,
  p_interaction_id uuid default null,
  p_type text default 'instructionView',
  p_duration integer default 0,
  p_details jsonb default '{}'::jsonb,
  p_cache_update jsonb default '{}'::jsonb,
  p_insert_progress boolean default true
)
returns table (
  progress jsonb,
  enrollment jsonb
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_enrollment public.enrollment%rowtype;
  v_progress_row public.progress%rowtype;
  v_progress jsonb;
  v_entry jsonb;
  v_scores jsonb;
  v_timestamp timestamptz := now();
  v_duration integer := greatest(coalesce(p_duration, 0), 0);
  v_time_delta integer := 0;
  v_legacy_id text;
  v_score jsonb;
begin
  if auth.uid() is not null and auth.uid() <> p_user_id then
    raise exception 'User is not authorized to record progress for this enrollment';
  end if;

  select *
  into v_enrollment
  from public.enrollment
  where id = p_enrollment_id
  for update;

  if not found then
    raise exception 'Enrollment not found';
  end if;

  if v_enrollment."learnerId" <> p_user_id then
    raise exception 'User is not authorized to record progress for this enrollment';
  end if;

  if v_enrollment."catalogId" <> p_catalog_id then
    raise exception 'Enrollment does not belong to the requested course';
  end if;

  if p_insert_progress then
    insert into public.progress ("userId", "catalogId", "enrollmentId", "topicId", "interactionId", duration, type, details)
    values (p_user_id, p_catalog_id, p_enrollment_id, p_topic_id, p_interaction_id, v_duration, p_type, coalesce(p_details, '{}'::jsonb))
    returning * into v_progress_row;

    v_timestamp := v_progress_row."createdAt";
  end if;

  v_progress := coalesce(v_enrollment.progress, '{}'::jsonb);

  if p_topic_id is not null and coalesce((p_cache_update->>'touchTopic')::boolean, false) then
    v_entry := coalesce(v_progress -> p_topic_id::text, '{}'::jsonb);
    if jsonb_typeof(v_entry) <> 'object' then
      v_entry := '{}'::jsonb;
    end if;
    if jsonb_typeof(coalesce(v_entry->'scores', '{}'::jsonb)) <> 'object' then
      v_entry := jsonb_set(v_entry, '{scores}', '{}'::jsonb, true);
    end if;

    if (p_cache_update->>'timeSpentDelta') ~ '^[0-9]+$' then
      v_time_delta := greatest((p_cache_update->>'timeSpentDelta')::integer, 0);
    end if;

    if v_time_delta > 0 then
      v_entry := jsonb_set(v_entry, '{timeSpent}', to_jsonb(coalesce((v_entry->>'timeSpent')::integer, 0) + v_time_delta), true);
    end if;

    v_score := p_cache_update->'score';
    if jsonb_typeof(v_score) = 'object' and coalesce(v_score->>'interactionId', '') <> '' then
      v_scores := coalesce(v_entry->'scores', '{}'::jsonb);
      if (v_score->>'percentCorrect') ~ '^-?[0-9]+(\.[0-9]+)?$' then
        v_scores := v_scores || jsonb_build_object(v_score->>'interactionId', (v_score->>'percentCorrect')::numeric);
      else
        v_scores := v_scores || jsonb_build_object(v_score->>'interactionId', null);
      end if;

      if jsonb_typeof(v_entry->'interactions') = 'array' then
        for v_legacy_id in select jsonb_array_elements_text(v_entry->'interactions')
        loop
          if not (v_scores ? v_legacy_id) then
            v_scores := v_scores || jsonb_build_object(v_legacy_id, null);
          end if;
        end loop;
        v_entry := v_entry - 'interactions';
      end if;

      v_entry := jsonb_set(v_entry, '{scores}', v_scores, true);
    end if;

    if coalesce((p_cache_update->>'touchTopicActivity')::boolean, false) then
      v_entry := jsonb_set(v_entry, '{lastInteractionAt}', to_jsonb(v_timestamp), true);
    end if;

    if coalesce((p_cache_update->>'projectSubmission')::boolean, false) then
      v_entry := jsonb_set(v_entry, '{projectSubmission}', 'true'::jsonb, true);
    end if;

    if coalesce((p_cache_update->>'notes')::boolean, false) then
      v_entry := jsonb_set(v_entry, '{notes}', 'true'::jsonb, true);
    end if;

    if coalesce((p_cache_update->>'examCompleted')::boolean, false) then
      v_entry := jsonb_set(v_entry, '{examCompleted}', 'true'::jsonb, true);
    end if;

    if p_cache_update ? 'draState' then
      v_entry := jsonb_set(v_entry, '{draState}', to_jsonb(p_cache_update->>'draState'), true);
    end if;
    if p_cache_update ? 'mode' then
      v_entry := jsonb_set(v_entry, '{mode}', to_jsonb(p_cache_update->>'mode'), true);
    end if;
    if (p_cache_update->>'itemsCompleted') ~ '^[0-9]+$' then
      v_entry := jsonb_set(v_entry, '{itemsCompleted}', to_jsonb((p_cache_update->>'itemsCompleted')::integer), true);
    end if;
    if (p_cache_update->>'totalItems') ~ '^[0-9]+$' then
      v_entry := jsonb_set(v_entry, '{totalItems}', to_jsonb((p_cache_update->>'totalItems')::integer), true);
    end if;
    if (p_cache_update->>'masteryScore') ~ '^-?[0-9]+(\.[0-9]+)?$' then
      v_entry := jsonb_set(v_entry, '{masteryScore}', to_jsonb((p_cache_update->>'masteryScore')::numeric), true);
    end if;
    if coalesce((p_cache_update->>'draCompleted')::boolean, false) then
      v_entry := jsonb_set(v_entry, '{draCompleted}', 'true'::jsonb, true);
    end if;

    if p_cache_update ? 'interviewState' then
      v_entry := jsonb_set(v_entry, '{interviewState}', to_jsonb(p_cache_update->>'interviewState'), true);
    end if;
    if (p_cache_update->>'sessionsCompleted') ~ '^[0-9]+$' then
      v_entry := jsonb_set(v_entry, '{sessionsCompleted}', to_jsonb((p_cache_update->>'sessionsCompleted')::integer), true);
    end if;
    if (p_cache_update->>'totalSessions') ~ '^[0-9]+$' then
      v_entry := jsonb_set(v_entry, '{totalSessions}', to_jsonb((p_cache_update->>'totalSessions')::integer), true);
    end if;
    if coalesce((p_cache_update->>'interviewCompleted')::boolean, false) then
      v_entry := jsonb_set(v_entry, '{interviewCompleted}', 'true'::jsonb, true);
    end if;

    v_progress := jsonb_set(v_progress, array[p_topic_id::text], v_entry, true);
  end if;

  if coalesce((p_cache_update->>'touchActivity')::boolean, false) then
    v_progress := jsonb_set(v_progress, '{lastActivityAt}', to_jsonb(v_timestamp), true);
  end if;

  update public.enrollment
  set progress = v_progress
  where id = p_enrollment_id
  returning * into v_enrollment;

  progress := case when p_insert_progress then to_jsonb(v_progress_row) else null end;
  enrollment := to_jsonb(v_enrollment);
  return next;
end;
$$;

-- RPC for free-text topic search with highlighted snippets
create or replace function public.search_topics(search_query text, target_catalog_id uuid default null)
returns table (
  id uuid,
  "catalogId" uuid,
  headline text,
  rank real
)
language plpgsql
as $$
begin
  return query
  select
    t.id,
    t."catalogId",
    ts_headline(
      'english',
      t.content,
      websearch_to_tsquery('english', search_query),
      'StartSel="<mark>", StopSel="</mark>", MaxWords=10, MinWords=5, MaxFragments=3, FragmentDelimiter=" ... "'
    ) as headline,
    ts_rank(t."ftsContent", websearch_to_tsquery('english', search_query)) as rank
  from public.topic t
  where t."ftsContent" @@ websearch_to_tsquery('english', search_query)
    and (target_catalog_id is null or t."catalogId" = target_catalog_id)
  order by rank desc;
end;
$$;

-- Security helper: true when user has root role
create or replace function public.auth_is_root(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.role
    where "user" = uid
      and "right" = 'root'
  );
$$;

-- Security helper: true when user has editor role
create or replace function public.auth_is_editor(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.role
    where "user" = uid
      and "right" = 'editor'
  );
$$;

-- Security helper: true when user has mentor role
create or replace function public.auth_is_mentor(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.role
    where "user" = uid
      and "right" = 'mentor'
  );
$$;

-- Security helper: true when user can manage a specific course
create or replace function public.auth_manages_course(uid uuid, catalog_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select (
    public.auth_is_root(uid)
    or exists (
      select 1
      from public.role
      where "user" = uid
        and "right" = 'editor'
        and object = catalog_id
    )
  );
$$;

-- Security helper: true when user can oversee a specific course without editing it
create or replace function public.auth_oversees_course(uid uuid, catalog_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select (
    public.auth_manages_course(uid, catalog_id)
    or exists (
      select 1
      from public.role
      where "user" = uid
        and "right" = 'mentor'
        and object = catalog_id
    )
  );
$$;

-- Security helper: true when user can oversee a course that the target learner is enrolled in
create or replace function public.auth_oversees_enrolled_user(uid uuid, target_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.enrollment e
    where e."learnerId" = target_user_id
      and public.auth_oversees_course(uid, e."catalogId")
  );
$$;



----------------------- Trigger


-- Trigger to apply updateModifiedColumn on topic updates
drop trigger if exists "updateTopicModtime" on public.topic;
create trigger "updateTopicModtime"
before update on public.topic
for each row
execute procedure public."updateModifiedColumn"();

-- Mirror auth.users.email changes into public.user.email so the app sees the
-- new email immediately after the user confirms an email change, without
-- waiting for the next sign-in to run _ensureUserRecord. security definer is
-- required because public.user RLS otherwise blocks cross-row updates.
create or replace function public.sync_public_user_email()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.user set email = NEW.email where id = NEW.id;
  return NEW;
end;
$$;

drop trigger if exists "syncPublicUserEmail" on auth.users;
create trigger "syncPublicUserEmail"
after update of email on auth.users
for each row
when (OLD.email is distinct from NEW.email)
execute function public.sync_public_user_email();




----------------------- Grants


-- Allow clients to execute role-check helper functions from policies
grant execute on function public.auth_is_root(uuid) to authenticated;
grant execute on function public.auth_is_editor(uuid) to authenticated;
grant execute on function public.auth_is_mentor(uuid) to authenticated;
grant execute on function public.auth_manages_course(uuid, uuid) to authenticated;
grant execute on function public.auth_oversees_course(uuid, uuid) to authenticated;
grant execute on function public.auth_oversees_enrolled_user(uuid, uuid) to authenticated;
grant execute on function public.record_progress_event(uuid, uuid, uuid, uuid, uuid, text, integer, jsonb, jsonb, boolean) to authenticated;

-- Define table grants by first revoking everything
revoke all on table public.catalog from public, anon, authenticated;
revoke all on table public."user" from public, anon, authenticated;
revoke all on table public.role from public, anon, authenticated;
revoke all on table public.enrollment from public, anon, authenticated;
revoke all on table public.topic from public, anon, authenticated;
revoke all on table public.progress from public, anon, authenticated;
revoke all on table public.log from public, anon, authenticated;

-- Catalog grants
grant select on table public.catalog to anon, authenticated;
grant insert, update, delete on table public.catalog to authenticated;

-- Authenticated users can attempt read/write user profiles (RLS will narrow to self)
grant select, insert, update, delete on table public."user" to authenticated;

-- Authenticated users can attempt read/write role assignments (RLS will narrow to role)
grant select, insert, update, delete on table public.role to authenticated;

-- Authenticated users can attempt read/write enrollment records (RLS will narrow to self)
grant select, insert, update, delete on table public.enrollment to authenticated;

-- Authenticated users can attempt read/write topic content (RLS will narrow to role)
grant select, insert, update, delete on table public.topic to authenticated;

-- Authenticated users can attempt read/write progress records (RLS will narrow to self)
grant select, insert, update, delete on table public.progress to authenticated;

-- Any registered user can insert a log entry; RLS narrows reads to root/editor. Logs are
-- append-only, so update/delete are intentionally not granted to anyone.
grant select, insert on table public.log to authenticated;


----------------------- Row Level Security


-- Enable RLS on all application tables
alter table public.catalog enable row level security;
alter table public."user" enable row level security;
alter table public.role enable row level security;
alter table public.enrollment enable row level security;
alter table public.topic enable row level security;
alter table public.progress enable row level security;
alter table public.log enable row level security;


----------------------- Policies


-- Clear all table policies so re-runs are deterministic
drop policy if exists "World read all" on public.catalog;
drop policy if exists "Editor creates catalog" on public.catalog;
drop policy if exists "Course editor updates course" on public.catalog;
drop policy if exists "Course editor deletes course" on public.catalog;
drop policy if exists "Root manages all" on public.catalog;
drop policy if exists "User manage self" on public."user";
drop policy if exists "Editor reads all users" on public."user";
drop policy if exists "Course overseer reads enrolled users" on public."user";
drop policy if exists "Root manages all" on public."user";
drop policy if exists "User read self" on public.role;
drop policy if exists "Course editor reads course roles" on public.role;
drop policy if exists "Course editor inserts course roles" on public.role;
drop policy if exists "Course editor updates course roles" on public.role;
drop policy if exists "Course editor deletes course roles" on public.role;
drop policy if exists "Root manages all" on public.role;
drop policy if exists "User manage self" on public.enrollment;
drop policy if exists "Course overseer reads course enrollments" on public.enrollment;
drop policy if exists "Root manages all" on public.enrollment;
drop policy if exists "User read all" on public.topic;
drop policy if exists "Course editor manages topics" on public.topic;
drop policy if exists "Root manages all" on public.topic;
drop policy if exists "Allow users to insert their own progress" on public.progress;
drop policy if exists "Allow users to read their own progress" on public.progress;
drop policy if exists "Editor reads all users progress" on public.progress;
drop policy if exists "Editor reads managed course progress" on public.progress;
drop policy if exists "Root manages all" on public.progress;
drop policy if exists "Registered user inserts log" on public.log;
drop policy if exists "Root or editor reads log" on public.log;


----------------------- Policies: Catalog


create policy "World read all"
on public.catalog
for select
to public
using (true);

create policy "Editor creates catalog"
on public.catalog
for insert
to authenticated
with check (
  public.auth_is_editor(auth.uid())
  and "createdBy" = auth.uid()
);

create policy "Course editor updates course"
on public.catalog
for update
to authenticated
using (public.auth_manages_course(auth.uid(), id))
with check (public.auth_manages_course(auth.uid(), id));

create policy "Course editor deletes course"
on public.catalog
for delete
to authenticated
using (public.auth_manages_course(auth.uid(), id));

create policy "Root manages all"
on public.catalog
for all
to authenticated
using (public.auth_is_root(auth.uid()))
with check (public.auth_is_root(auth.uid()));


----------------------- Policies: User


create policy "User manage self"
on public."user"
for all
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "Editor reads all users"
on public."user"
for select
to authenticated
using (public.auth_is_editor(auth.uid()));

create policy "Course overseer reads enrolled users"
on public."user"
for select
to authenticated
using (public.auth_oversees_enrolled_user(auth.uid(), id));

create policy "Root manages all"
on public."user"
for all
to authenticated
using (public.auth_is_root(auth.uid()))
with check (public.auth_is_root(auth.uid()));


----------------------- Policies: Role


create policy "User read self"
on public.role
for select
to authenticated
using ("user" = auth.uid());

create policy "Course editor reads course roles"
on public.role
for select
to authenticated
using (
  "right" in ('editor', 'mentor')
  and object is not null
  and public.auth_manages_course(auth.uid(), object)
);

create policy "Course editor inserts course roles"
on public.role
for insert
to authenticated
with check (
  "right" in ('editor', 'mentor')
  and object is not null
  and (
    public.auth_manages_course(auth.uid(), object)
    or (
      "user" = auth.uid()
      and exists (
        select 1
        from public.catalog c
        where c.id = object
          and c."createdBy" = auth.uid()
      )
    )
  )
);

create policy "Course editor updates course roles"
on public.role
for update
to authenticated
using (
  "right" in ('editor', 'mentor')
  and object is not null
  and public.auth_manages_course(auth.uid(), object)
)
with check (
  "right" in ('editor', 'mentor')
  and object is not null
  and public.auth_manages_course(auth.uid(), object)
);

create policy "Course editor deletes course roles"
on public.role
for delete
to authenticated
using (
  "right" in ('editor', 'mentor')
  and object is not null
  and public.auth_manages_course(auth.uid(), object)
);

create policy "Root manages all"
on public.role
for all
to authenticated
using (public.auth_is_root(auth.uid()))
with check (public.auth_is_root(auth.uid()));


----------------------- Policies: Enrollment


create policy "User manage self"
on public.enrollment
for all
to authenticated
using (auth.uid() = "learnerId")
with check (auth.uid() = "learnerId");

create policy "Course overseer reads course enrollments"
on public.enrollment
for select
to authenticated
using (public.auth_oversees_course(auth.uid(), "catalogId"));

create policy "Root manages all"
on public.enrollment
for all
to authenticated
using (public.auth_is_root(auth.uid()))
with check (public.auth_is_root(auth.uid()));


----------------------- Policies: Topic


create policy "User read all"
on public.topic
for select
to authenticated
using (true);

create policy "Course editor manages topics"
on public.topic
for all
to authenticated
using (public.auth_manages_course(auth.uid(), "catalogId"))
with check (public.auth_manages_course(auth.uid(), "catalogId"));

create policy "Root manages all"
on public.topic
for all
to authenticated
using (public.auth_is_root(auth.uid()))
with check (public.auth_is_root(auth.uid()));


----------------------- Policies: Progress


create policy "Allow users to insert their own progress"
on public.progress
for insert
to authenticated
with check (auth.uid() = "userId");

create policy "Allow users to read their own progress"
on public.progress
for select
to authenticated
using (auth.uid() = "userId");

create policy "Editor reads managed course progress"
on public.progress
for select
to authenticated
using (public.auth_oversees_course(auth.uid(), "catalogId"));

create policy "Root manages all"
on public.progress
for all
to authenticated
using (public.auth_is_root(auth.uid()))
with check (public.auth_is_root(auth.uid()));


----------------------- Policies: Log


create policy "Registered user inserts log"
on public.log
for insert
to authenticated
with check ("generatedBy" = auth.uid());

create policy "Root or editor reads log"
on public.log
for select
to authenticated
using (public.auth_is_root(auth.uid()) or public.auth_is_editor(auth.uid()));

-- =====================================================================
-- File submission storage bucket + RLS
-- =====================================================================

-- Private bucket, 100KB per-object cap, MIME allowlist enforced by Storage.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'submissions',
  'submissions',
  false,
  102400,
  array['image/png','image/jpeg','image/webp','application/pdf','application/zip','application/x-zip-compressed']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Helper: pull the enrollment id out of an object name shaped like
-- "enrollments/{enrollmentId}/interactions/{interactionId}/{uuid}_{name}".
create or replace function public.submission_enrollment_id(object_name text)
returns uuid
language sql
stable
as $$
  select case
    when split_part(object_name, '/', 1) = 'enrollments'
      then nullif(split_part(object_name, '/', 2), '')::uuid
    else null
  end;
$$;

grant execute on function public.submission_enrollment_id(text) to authenticated;

-- Learner can write into their own enrollment folder.
create policy "submissions: learner inserts own"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'submissions'
  and exists (
    select 1 from public.enrollment e
    where e.id = public.submission_enrollment_id(name)
      and e."learnerId" = auth.uid()
  )
);

-- Learner reads own; course overseer (root/editor/mentor) reads anyone enrolled in courses they oversee.
create policy "submissions: learner or course manager reads"
on storage.objects for select
to authenticated
using (
  bucket_id = 'submissions'
  and exists (
    select 1 from public.enrollment e
    where e.id = public.submission_enrollment_id(name)
      and (e."learnerId" = auth.uid() or public.auth_oversees_course(auth.uid(), e."catalogId"))
  )
);

-- Learner deletes own (for replace-on-resubmit); course manager can also delete.
create policy "submissions: learner or course manager deletes"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'submissions'
  and exists (
    select 1 from public.enrollment e
    where e.id = public.submission_enrollment_id(name)
      and (e."learnerId" = auth.uid() or public.auth_manages_course(auth.uid(), e."catalogId"))
  )
);


-- =====================================================================
-- DRA state storage bucket
-- =====================================================================

-- Private bucket, 1MB per-object cap, JSON only.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'dra-state',
  'dra-state',
  false,
  1048576,
  array['application/json']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Helper: pull enrollment id out of "enrollments/{enrollmentId}/topics/{topicId}/state.json".
create or replace function public.dra_state_enrollment_id(object_name text)
returns uuid
language sql
stable
as $$
  select case
    when split_part(object_name, '/', 1) = 'enrollments'
      then nullif(split_part(object_name, '/', 2), '')::uuid
    else null
  end;
$$;

grant execute on function public.dra_state_enrollment_id(text) to authenticated;

create policy "dra-state: learner inserts own"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'dra-state'
  and exists (
    select 1 from public.enrollment e
    where e.id = public.dra_state_enrollment_id(name)
      and e."learnerId" = auth.uid()
  )
);

create policy "dra-state: learner updates own"
on storage.objects for update
to authenticated
using (
  bucket_id = 'dra-state'
  and exists (
    select 1 from public.enrollment e
    where e.id = public.dra_state_enrollment_id(name)
      and e."learnerId" = auth.uid()
  )
);

create policy "dra-state: learner or manager reads"
on storage.objects for select
to authenticated
using (
  bucket_id = 'dra-state'
  and exists (
    select 1 from public.enrollment e
    where e.id = public.dra_state_enrollment_id(name)
      and (e."learnerId" = auth.uid() or public.auth_oversees_course(auth.uid(), e."catalogId"))
  )
);

create policy "dra-state: learner or manager deletes"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'dra-state'
  and exists (
    select 1 from public.enrollment e
    where e.id = public.dra_state_enrollment_id(name)
      and (e."learnerId" = auth.uid() or public.auth_manages_course(auth.uid(), e."catalogId"))
  )
);
