-- Needed for gen_random_uuid()
create extension if not exists pgcrypto;

-- Execution order:
--   1) Tables + Indexes
--   2) Functions + Triggers
--   3) Grants
--   4) RLS enablement
--   5) Policies




----------------------- Tables


-- Course catalog metadata
create table if not exists public.catalog (
  id uuid primary key default gen_random_uuid(),
  "createdAt" timestamp with time zone default now(),
  "createdBy" uuid references auth.users(id) on delete set null default auth.uid(),
  title text,
  description text,
  name text,
  "gitHub" jsonb default '{}'::jsonb,
  settings jsonb default '{}'::jsonb
);

-- Profile row for each authenticated user
create table if not exists public."user" (
  id uuid not null references auth.users(id) on delete cascade,
  "createdAt" timestamp with time zone default now(),
  name text,
  email text,
  settings jsonb default '{}'::jsonb,
  primary key (id)
);

-- Role assignments (root/editor, etc.)
create table if not exists public.role (
  id bigint generated by default as identity primary key,
  "createdAt" timestamp with time zone default now(),
  "user" uuid references auth.users(id) on delete cascade,
  "right" varchar,
  object uuid references public.catalog(id) on delete cascade,
  settings jsonb default '{}'::jsonb
);

-- User enrollment in a catalog/course
create table if not exists public.enrollment (
  id uuid primary key default gen_random_uuid(),
  "createdAt" timestamp with time zone default now(),
  "learnerId" uuid references public."user"(id) on delete cascade,
  "catalogId" uuid references public.catalog(id) on delete cascade,
  progress jsonb default '{}'::jsonb,
  settings jsonb default '{}'::jsonb
);

-- Topic content cache with full-text search index source column
create table if not exists public.topic (
  id uuid primary key,
  "catalogId" uuid references public.catalog(id) on delete cascade,
  content text not null,
  ftsContent tsvector generated always as (to_tsvector('english', ' ' || content)) stored,
  "updatedAt" timestamp with time zone default now()
);

-- Progress/event tracking per user/topic
create table if not exists public.progress (
  id uuid primary key default gen_random_uuid(),
  "createdAt" timestamp with time zone default now(),
  "userId" uuid references public."user"(id) on delete cascade,
  "enrollmentId" uuid references public.enrollment(id) on delete cascade,
  "catalogId" uuid references public.catalog(id) on delete cascade,
  "topicId" uuid,
  "interactionId" uuid,
  duration integer,
  type varchar,
  details jsonb default '{}'::jsonb
);


----------------------- Indexes


-- Full-text search GIN index
create index if not exists "topicFtsIdx" on public.topic using gin (ftsContent);

-- Auth checks in gradebookoverview edge function
create index if not exists "roleUserRightObjectIdx" on public.role ("user", "right", object);

-- Course ownership bootstrap checks during editor course creation
create index if not exists "catalogCreatedByIdx" on public.catalog ("createdBy");

-- Enrollment lookups by course, and learner auth check
create index if not exists "enrollmentCatalogIdx" on public.enrollment ("catalogId");
create index if not exists "enrollmentCatalogLearnerIdx" on public.enrollment ("catalogId", "learnerId");

-- Progress queries: by enrollment+type (detail view, interaction history, notes, exam state)
create index if not exists "progressEnrollmentTypeIdx" on public.progress ("enrollmentId", type);

-- Progress queries: by catalog+topic+interaction (survey/Likert summaries)
create index if not exists "progressCatalogTopicIdx" on public.progress ("catalogId", "topicId", "interactionId");


----------------------- Functions


-- Trigger function to keep topic updated timestamp current
create or replace function public."updateModifiedColumn"()
returns trigger
language plpgsql
as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$;

-- RPC for free-text topic search with highlighted snippets
create or replace function public.search_topics(search_query text, target_catalog_id uuid default null)
returns table (
  id uuid,
  "catalogId" uuid,
  headline text,
  rank real
)
language plpgsql
as $$
begin
  return query
  select
    t.id,
    t."catalogId",
    ts_headline(
      'english',
      t.content,
      websearch_to_tsquery('english', search_query),
      'StartSel="<mark>", StopSel="</mark>", MaxWords=10, MinWords=5, MaxFragments=3, FragmentDelimiter=" ... "'
    ) as headline,
    ts_rank(t."ftsContent", websearch_to_tsquery('english', search_query)) as rank
  from public.topic t
  where t."ftsContent" @@ websearch_to_tsquery('english', search_query)
    and (target_catalog_id is null or t."catalogId" = target_catalog_id)
  order by rank desc;
end;
$$;

-- Security helper: true when user has root role
create or replace function public.auth_is_root(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.role
    where "user" = uid
      and "right" = 'root'
  );
$$;

-- Security helper: true when user has editor role
create or replace function public.auth_is_editor(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.role
    where "user" = uid
      and "right" = 'editor'
  );
$$;

-- Security helper: true when user can manage a specific course
create or replace function public.auth_manages_course(uid uuid, catalog_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select (
    public.auth_is_root(uid)
    or exists (
      select 1
      from public.role
      where "user" = uid
        and "right" = 'editor'
        and object = catalog_id
    )
  );
$$;



----------------------- Trigger


-- Trigger to apply updateModifiedColumn on topic updates
drop trigger if exists "updateTopicModtime" on public.topic;
create trigger "updateTopicModtime"
before update on public.topic
for each row
execute procedure public."updateModifiedColumn"();

-- Mirror auth.users.email changes into public.user.email so the app sees the
-- new email immediately after the user confirms an email change, without
-- waiting for the next sign-in to run _ensureUserRecord. security definer is
-- required because public.user RLS otherwise blocks cross-row updates.
create or replace function public.sync_public_user_email()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.user set email = NEW.email where id = NEW.id;
  return NEW;
end;
$$;

drop trigger if exists "syncPublicUserEmail" on auth.users;
create trigger "syncPublicUserEmail"
after update of email on auth.users
for each row
when (OLD.email is distinct from NEW.email)
execute function public.sync_public_user_email();




----------------------- Grants


-- Allow clients to execute role-check helper functions from policies
grant execute on function public.auth_is_root(uuid) to authenticated;
grant execute on function public.auth_is_editor(uuid) to authenticated;
grant execute on function public.auth_manages_course(uuid, uuid) to authenticated;

-- Define table grants by first revoking everything
revoke all on table public.catalog from public, anon, authenticated;
revoke all on table public."user" from public, anon, authenticated;
revoke all on table public.role from public, anon, authenticated;
revoke all on table public.enrollment from public, anon, authenticated;
revoke all on table public.topic from public, anon, authenticated;
revoke all on table public.progress from public, anon, authenticated;

-- Catalog grants
grant select on table public.catalog to anon, authenticated;
grant insert, update, delete on table public.catalog to authenticated;

-- Authenticated users can attempt read/write user profiles (RLS will narrow to self)
grant select, insert, update, delete on table public."user" to authenticated;

-- Authenticated users can attempt read/write role assignments (RLS will narrow to role)
grant select, insert, update, delete on table public.role to authenticated;

-- Authenticated users can attempt read/write enrollment records (RLS will narrow to self)
grant select, insert, update, delete on table public.enrollment to authenticated;

-- Authenticated users can attempt read/write topic content (RLS will narrow to role)
grant select, insert, update, delete on table public.topic to authenticated;

-- Authenticated users can attempt read/write progress records (RLS will narrow to self)
grant select, insert, update, delete on table public.progress to authenticated;


----------------------- Row Level Security


-- Enable RLS on all application tables
alter table public.catalog enable row level security;
alter table public."user" enable row level security;
alter table public.role enable row level security;
alter table public.enrollment enable row level security;
alter table public.topic enable row level security;
alter table public.progress enable row level security;


----------------------- Policies


-- Clear all table policies so re-runs are deterministic
drop policy if exists "World read all" on public.catalog;
drop policy if exists "Editor creates catalog" on public.catalog;
drop policy if exists "Course editor updates course" on public.catalog;
drop policy if exists "Course editor deletes course" on public.catalog;
drop policy if exists "Root manages all" on public.catalog;
drop policy if exists "User manage self" on public."user";
drop policy if exists "Editor reads all users" on public."user";
drop policy if exists "Root manages all" on public."user";
drop policy if exists "User read self" on public.role;
drop policy if exists "Course editor reads course roles" on public.role;
drop policy if exists "Course editor inserts course roles" on public.role;
drop policy if exists "Course editor updates course roles" on public.role;
drop policy if exists "Course editor deletes course roles" on public.role;
drop policy if exists "Root manages all" on public.role;
drop policy if exists "User manage self" on public.enrollment;
drop policy if exists "Root manages all" on public.enrollment;
drop policy if exists "User read all" on public.topic;
drop policy if exists "Root manages all" on public.topic;
drop policy if exists "Allow users to insert their own progress" on public.progress;
drop policy if exists "Allow users to read their own progress" on public.progress;
drop policy if exists "Editor reads all users progress" on public.progress;
drop policy if exists "Root manages all" on public.progress;


----------------------- Policies: Catalog


create policy "World read all"
on public.catalog
for select
to public
using (true);

create policy "Editor creates catalog"
on public.catalog
for insert
to authenticated
with check (
  public.auth_is_editor(auth.uid())
  and "createdBy" = auth.uid()
);

create policy "Course editor updates course"
on public.catalog
for update
to authenticated
using (public.auth_manages_course(auth.uid(), id))
with check (public.auth_manages_course(auth.uid(), id));

create policy "Course editor deletes course"
on public.catalog
for delete
to authenticated
using (public.auth_manages_course(auth.uid(), id));

create policy "Root manages all"
on public.catalog
for all
to authenticated
using (public.auth_is_root(auth.uid()))
with check (public.auth_is_root(auth.uid()));


----------------------- Policies: User


create policy "User manage self"
on public."user"
for all
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "Editor reads all users"
on public."user"
for select
to authenticated
using (public.auth_is_editor(auth.uid()));

create policy "Root manages all"
on public."user"
for all
to authenticated
using (public.auth_is_root(auth.uid()))
with check (public.auth_is_root(auth.uid()));


----------------------- Policies: Role


create policy "User read self"
on public.role
for select
to authenticated
using ("user" = auth.uid());

create policy "Course editor reads course roles"
on public.role
for select
to authenticated
using (
  "right" = 'editor'
  and object is not null
  and public.auth_manages_course(auth.uid(), object)
);

create policy "Course editor inserts course roles"
on public.role
for insert
to authenticated
with check (
  "right" = 'editor'
  and object is not null
  and (
    public.auth_manages_course(auth.uid(), object)
    or (
      "user" = auth.uid()
      and exists (
        select 1
        from public.catalog c
        where c.id = object
          and c."createdBy" = auth.uid()
      )
    )
  )
);

create policy "Course editor updates course roles"
on public.role
for update
to authenticated
using (
  "right" = 'editor'
  and object is not null
  and public.auth_manages_course(auth.uid(), object)
)
with check (
  "right" = 'editor'
  and object is not null
  and public.auth_manages_course(auth.uid(), object)
);

create policy "Course editor deletes course roles"
on public.role
for delete
to authenticated
using (
  "right" = 'editor'
  and object is not null
  and public.auth_manages_course(auth.uid(), object)
);

create policy "Root manages all"
on public.role
for all
to authenticated
using (public.auth_is_root(auth.uid()))
with check (public.auth_is_root(auth.uid()));


----------------------- Policies: Enrollment


create policy "User manage self"
on public.enrollment
for all
to authenticated
using (auth.uid() = "learnerId")
with check (auth.uid() = "learnerId");

create policy "Root manages all"
on public.enrollment
for all
to authenticated
using (public.auth_is_root(auth.uid()))
with check (public.auth_is_root(auth.uid()));


----------------------- Policies: Topic


create policy "User read all"
on public.topic
for select
to authenticated
using (true);

create policy "Root manages all"
on public.topic
for all
to authenticated
using (public.auth_is_root(auth.uid()))
with check (public.auth_is_root(auth.uid()));


----------------------- Policies: Progress


create policy "Allow users to insert their own progress"
on public.progress
for insert
to authenticated
with check (auth.uid() = "userId");

create policy "Allow users to read their own progress"
on public.progress
for select
to authenticated
using (auth.uid() = "userId");

create policy "Editor reads all users progress"
on public.progress
for select
to authenticated
using (public.auth_is_editor(auth.uid()));

create policy "Root manages all"
on public.progress
for all
to authenticated
using (public.auth_is_root(auth.uid()))
with check (public.auth_is_root(auth.uid()));

-- =====================================================================
-- File submission storage bucket + RLS
-- =====================================================================

-- Private bucket, 100KB per-object cap, MIME allowlist enforced by Storage.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'submissions',
  'submissions',
  false,
  102400,
  array['image/png','image/jpeg','image/webp','application/pdf','application/zip','application/x-zip-compressed']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Helper: pull the enrollment id out of an object name shaped like
-- "enrollments/{enrollmentId}/interactions/{interactionId}/{uuid}_{name}".
create or replace function public.submission_enrollment_id(object_name text)
returns uuid
language sql
stable
as $$
  select case
    when split_part(object_name, '/', 1) = 'enrollments'
      then nullif(split_part(object_name, '/', 2), '')::uuid
    else null
  end;
$$;

grant execute on function public.submission_enrollment_id(text) to authenticated;

-- Learner can write into their own enrollment folder.
create policy "submissions: learner inserts own"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'submissions'
  and exists (
    select 1 from public.enrollment e
    where e.id = public.submission_enrollment_id(name)
      and e."learnerId" = auth.uid()
  )
);

-- Learner reads own; course manager (editor/root) reads anyone enrolled in courses they manage.
create policy "submissions: learner or course manager reads"
on storage.objects for select
to authenticated
using (
  bucket_id = 'submissions'
  and exists (
    select 1 from public.enrollment e
    where e.id = public.submission_enrollment_id(name)
      and (e."learnerId" = auth.uid() or public.auth_manages_course(auth.uid(), e."catalogId"))
  )
);

-- Learner deletes own (for replace-on-resubmit); course manager can also delete.
create policy "submissions: learner or course manager deletes"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'submissions'
  and exists (
    select 1 from public.enrollment e
    where e.id = public.submission_enrollment_id(name)
      and (e."learnerId" = auth.uid() or public.auth_manages_course(auth.uid(), e."catalogId"))
  )
);


