-- Needed for gen_random_uuid()
create extension if not exists pgcrypto;

-- Course catalog metadata
create table if not exists public.catalog (
  id uuid primary key default gen_random_uuid(),
  "createdAt" timestamp with time zone default now(),
  title text,
  description text,
  name text,
  "gitHub" jsonb default '{}'::jsonb,
  settings jsonb default '{}'::jsonb
);

-- Profile row for each auth user
create table if not exists public."user" (
  id uuid not null references auth.users(id) on delete cascade,
  "createdAt" timestamp with time zone default now(),
  name text,
  email text,
  settings jsonb default '{}'::jsonb,
  primary key (id)
);

-- Role assignments (root/editor, etc.)
create table if not exists public.role (
  id bigint generated by default as identity primary key,
  "createdAt" timestamp with time zone default now(),
  "user" uuid references auth.users(id) on delete cascade,
  "right" varchar,
  object uuid references public.catalog(id) on delete cascade,
  settings jsonb default '{}'::jsonb
);

-- User enrollment in a catalog/course
create table if not exists public.enrollment (
  id uuid primary key default gen_random_uuid(),
  "createdAt" timestamp with time zone default now(),
  "learnerId" uuid references public."user"(id) on delete cascade,
  "catalogId" uuid references public.catalog(id) on delete cascade,
  progress jsonb default '{}'::jsonb,
  settings jsonb default '{}'::jsonb
);

-- Topic content cache with full-text search index source column
create table if not exists public.topic (
  id uuid primary key,
  "catalogId" uuid references public.catalog(id) on delete cascade,
  content text not null,
  ftsContent tsvector generated always as (to_tsvector('english', ' ' || content)) stored,
  "updatedAt" timestamp with time zone default now()
);

-- Full-text search GIN index
create index if not exists "topicFtsIdx" on public.topic using gin (ftsContent);

-- Progress/event tracking per user/topic
create table if not exists public.progress (
  id uuid primary key default gen_random_uuid(),
  "createdAt" timestamp with time zone default now(),
  "userId" uuid references public."user"(id) on delete cascade,
  "enrollmentId" uuid references public.enrollment(id) on delete cascade,
  "catalogId" uuid references public.catalog(id) on delete cascade,
  "topicId" uuid references public.topic(id) on delete cascade,
  "interactionId" uuid,
  duration integer,
  type varchar,
  details jsonb default '{}'::jsonb
);

-- Trigger function to keep topic updated timestamp current
create or replace function public."updateModifiedColumn"()
returns trigger
language plpgsql
as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$;

-- Trigger to apply updateModifiedColumn on topic updates
drop trigger if exists "updateTopicModtime" on public.topic;
create trigger "updateTopicModtime"
before update on public.topic
for each row
execute procedure public."updateModifiedColumn"();

-- RPC for free-text topic search with highlighted snippets
create or replace function public.search_topics(search_query text, target_catalog_id uuid default null)
returns table (
  id uuid,
  "catalogId" uuid,
  headline text,
  rank real
)
language plpgsql
as $$
begin
  return query
  select
    t.id,
    t."catalogId",
    ts_headline(
      'english',
      t.content,
      websearch_to_tsquery('english', search_query),
      'StartSel="<mark>", StopSel="</mark>", MaxWords=10, MinWords=5, MaxFragments=3, FragmentDelimiter=" ... "'
    ) as headline,
    ts_rank(t."ftsContent", websearch_to_tsquery('english', search_query)) as rank
  from public.topic t
  where t."ftsContent" @@ websearch_to_tsquery('english', search_query)
    and (target_catalog_id is null or t."catalogId" = target_catalog_id)
  order by rank desc;
end;
$$;

-- Security helper: true when user has root role
create or replace function public.auth_is_root(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.role
    where "user" = uid
      and "right" = 'root'
  );
$$;

-- Security helper: true when user has editor role
create or replace function public.auth_is_editor(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.role
    where "user" = uid
      and "right" = 'editor'
  );
$$;

-- Allow clients to execute role-check helper functions from policies
grant execute on function public.auth_is_root(uuid) to anon, authenticated;
grant execute on function public.auth_is_editor(uuid) to anon, authenticated;

-- Enable Row Level Security on all application tables
alter table public.catalog enable row level security;
alter table public."user" enable row level security;
alter table public.role enable row level security;
alter table public.enrollment enable row level security;
alter table public.topic enable row level security;
alter table public.progress enable row level security;
